CREATE DATABASE IF NOT EXISTS COP4331;
USE COP4331;

CREATE TABLE Users (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  FirstName VARCHAR(50) NOT NULL DEFAULT '',
  LastName  VARCHAR(50) NOT NULL DEFAULT '',
  Login     VARCHAR(50) NOT NULL DEFAULT '',
  Password  VARCHAR(255) NOT NULL DEFAULT ''
);

CREATE TABLE Contacts (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  FirstName VARCHAR(50) NOT NULL DEFAULT '',
  LastName  VARCHAR(50) NOT NULL DEFAULT '',
  Phone     VARCHAR(50) NOT NULL DEFAULT '',
  Email     VARCHAR(50) NOT NULL DEFAULT '',
  UserID    INT NOT NULL,
  INDEX idx_user_search (UserID, LastName, Email)
);
